name: Build

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    branches:
        - '**'

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  native-build:
    name: 'Native build'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Install required dependencies
      run: |
        python -m pip install https://github.com/hydrogram/hydrogram/archive/dev.zip tgcrypto aiofiles
    - name: Run
      env: 
        SESSION_STRING: ${{ secrets.SESSION_STRING }}
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        python -B main.py